### PR TITLE
Missing spaces in prefix declarations

### PR DESCRIPTION
**Pull request by dr-shorthair**

### CODE REVIEW

**Comment by situx** [comment]
Thank you for the hint!
As I generate the ontology using the python script you can find in the repository I fixed the issue in the python script and the namespaces should be fine now

**Comment by dr-shorthair** [comment]
Don't you use [RDFLib](https://github.com/RDFLib)? That would relieve you from worrying about the mechanics of serialization.

**Comment by situx** [comment]
Yes, I should consider doing that. Currently, I create a set of strings consisting of triples and write those to a file.
Was enough for now, but probably better to migrate in the future.

**Comment by dr-shorthair** [comment]
Ah - that explains why it is more like N3 than TTL ;-)

**Comment by situx** [comment]
Correct, but now I included rdflib, so this issue is solved.

**Pull request closed without merging**
